global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'travel-agency-backend'
    static_configs:
      - targets: ['backend:4000']
    metrics_path: '/api/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'travel-agency-backend'
